apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-service
    app: demo-voting-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: demo-voting-app