apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: demo-voting-app
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    name: mongo
    app: demo-voting-app