apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: demo-voting-app
spec:
  clusterIP: None # Headless service for StatefulSet
  selector:
    name: mongo
    app: demo-voting-app
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017